config/routes.rb
Rails.application.routes.draw do

  devise_for :users
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: 'admin/sessions'
}

#管理者
  namespace :admin do
    resources :order_details, only: [:update]

    resources :orders, only: [:show, :update]

    resources :customers, only: [:index, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    root to: 'homes#top'
  end

#ユーザ
  scope module: :public do
  #namespace→scope moduleに変更
  #URLは変えず、ファイル構成だけ指定のパスにする(フォルダ名にはpublicをつけて、URLにはつけない)
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    #completeを追加　orders#showよりも上に記述しないとcompleteがid扱いされてしまう
    get 'orders/complete'

    #comfirmを追加
    post 'orders/comfirm'
    resources :orders, only: [:new, :create, :index, :show]#:comfirm, :complete, 

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]#:destroy_all, 

    #resources :customers, only: [:edit, :show, :update, :unsubscribe, :withdraw]
    #→customersはURLを変更しなければいけないのでresourcesは使えない
    #resourcesは基本の7つのみ使えるので、その他は手動で追加する(追加はto:不要)
    
    #customers
    #edit URLを「/customers/:id/edit」→「/customers/information/edit」に変更
    get 'customers/information/edit', to: 'customers#edit'
    #show URLを「/customers/:id(.:format)」→「customers/my_page」に変更
    get 'customers/my_page', to: 'customers#show'
    #update URLを「/customers/:id(.:format)」→「/customers/information」に変更
    patch '/customers/information', to: 'customers#update'
    #unsubscribeを追加、退会確認
    get '/customers/unsubscribe'
    #withdrawを追加、退会処理
    patch '/customers/withdraw'

    resources :items, only: [:index, :show]

    #'URL' => 'コントローラ#アクション', as: :Prefix(パスが入った変数)の変更
    get '/' => 'homes#top', as: :top
    get '/about' => 'homes#about'
  end
  
  #devise_for :admins
  #devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#resources :●●s, only: [:new, :index, :show, :edit, :create, :update, :destroy ]→７つだけ書ける
#その他は get(patchなどもOK) 'orders/show' => 'orders#show'と書く

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #customer1:cart_item多(n)の関係
  #cart_itemから見てcustomerは1→「belongs_to :customer」(属する)を記述する
  #customerから見てcart_itemは多(n)→「has_many :cart_items, dependent: :destroy」を記述する
  #has_many:・・・テーブル同士を関連付ける、dependent(依存): :destroy・・・親モデルの削除時に、紐づいている子モデルも一緒に削除される
  has_many :cart_items, dependent: :destroy

  #customer1:order多(n)の関係
  #orderから見てcustomerは1→「belongs_to :customer」(属する)を記述する
  #customerから見てorderは多(n)→「has_many :orders, dependent: :destroy」を記述する
  #has_many:・・・テーブル同士を関連付ける、dependent(依存): :destroy・・・親モデルの削除時に、紐づいている子モデルも一緒に削除される
  has_many :orders, dependent: :destroy

  #customer1:address多(n)の関係
  #addressから見てcustomerは1→「belongs_to :customer」(属する)を記述する
  #customerから見てaddressは多(n)→「has_many :addresses, dependent: :destroy」を記述する
  #has_many:・・・テーブル同士を関連付ける、dependent(依存): :destroy・・・親モデルの削除時に、紐づいている子モデルも一緒に削除される
  has_many :addresses, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  # ログインしていない場合、ヘッダーのボタンをクリックしたら強制的にログイン画面に移動する
  # except→ログイン画面への遷移を除外する→今回は除外するものがない
  before_action :authenticate_admin!

  def index
    #ページネーション、10件表示
    @page = Customer.all.page(params[:page]).per(10)
  end

  def show
    @show_admin_customer = Customer.find(params[:id])
    
  end

  def edit
    @edit_admin_customer = Customer.find(params[:id])
  end

  def update
    #editで編集後、会員詳細(show)に遷移する
    #@の変数は↑のeditに合わせているのではなく、render(失敗)したときの遷移先がedit画面なので、
    #そちらで使用されている@edit~と合わせる必要があり、結果的に↑と同じ変数名になる
    @edit_admin_customer = Customer.find(params[:id])
    if @edit_admin_customer.update(admin_customer_params)#updateのパラメータ
      flash[:success] = "会員情報を更新しました"
      redirect_to admin_customer_path#admin/customers#show
    else
      render :edit
    end

  end

  #投稿データのストロングパラメータ(セキュリティに関係する)
  #require/permitメソッド:DBの更新時、不要なパラメータを取り除く(必要なパラメータだけに絞り込む)
  #require(パラメータ群).permit(:変更可能なパラメータ名)
  #会員情報編集(edit)をした後、updateに遷移する
  private
  def admin_customer_params#updateのパラメータ
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--<h1>Admin::Customers#edit</h1>-->
<br>
<h1><span style="background-color:lightgray" class="m-5">　<%= @edit_admin_customer.last_name %><%= @edit_admin_customer.first_name %>さんの会員情報編集　</span></h1>
<br>
    <%= form_with model: @edit_admin_customer, url: admin_customer_path(@edit_admin_customer.id) do |f| %><!--url(遷移先):update-->

      <table border="0" class="mx-auto">
        <tr>
          <td height="50" width="200">会員ID</td>
          <td><%= @edit_admin_customer.id %></td>
        </tr>

        <tr>
          <td height="50"><%= f.label :"氏名" %></td>
          <!--autofocus: true：カーソルが移動して入力状態になる→htmlに１つだけ設定できる-->
          <!--姓-->
          <td width="250"><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
          <!--名-->
          <td><%= f.text_field :first_name, autocomplete: "first_name" %></td>
        </tr>
        
        <tr>
          <td height="50"><%= f.label :"フリガナ" %></td>
          <!--セイ-->
          <td><%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %></td>
          <!--メイ-->
          <td><%= f.text_field :first_name_kana, autocomplete: "first_name_kana" %></td>
        </tr>
        
        <tr>
          <td height="50"><%= f.label :"郵便番号" %></td>
          <td><%= f.text_field :postal_code, autocomplete: "postal_code" %></td>
        </tr>

        <tr>
          <td height="50"><%= f.label :"住所" %></td>
          <td colspan="2"><%= f.text_area :address, autocomplete: "address", size: "50" %></td>
        </tr>

        <tr>
          <td height="50"><%= f.label :"電話番号" %></td>
          <td><%= f.text_field :telephone_number, autocomplete: "telephone_number" %></td>
        </tr>

        <tr>
          <td height="50"><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email, autocomplete: "email" %></td>
        </tr>

        <tr>
          <td height="50"><%= f.label :"会員ステータス" %></td>
          <td><!--ラジオボタン-->
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
          </td>
        </tr>

        <tr>
          <td height="50"></td>
          <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
        </tr>
      </table>
<% end %>
<br>

app/views/admin/customers/index.html.erb
<!--<h1>Admin::Customers#index</h1>-->
<br>
<h1><span style="background-color:lightgray" class="m-5">　会員一覧　</span></h1>
<br>
<table class="table" style="display:flex; justify-content:center">
  <tr bgcolor="lightgray" height="50">
    <th width="150">会員ID</th>
    <th width="150">氏名</th>
    <th width="350">メールアドレス</th>
    <th width="150">会員ステータス</th>
  </tr>
  
  <% @page.each do |page| %>
    <tr height="50">
      <td><%= page.id %></td>
      <td><%=link_to page.last_name+page.first_name, admin_customer_path(page.id) %></td><!--show画面に遷移-->
      <td><%= page.email %></td>

        <% if page.is_deleted == false %>
      <td><font color="green">有効</font></td>
        <% else %>
      <td><font color="gray">退会</font></td>
        <% end %>
    </tr>
  <% end %>
</table>

<!--ページネーション-->
<!--https://getbootstrap.jp/→ドキュメント→検索-->
<div class="d-flex justify-content-center"><%= paginate @page %></div>
<br>

app/views/admin/customers/show.html.erb
<!--<h1>Admin::Customers#show</h1>-->
<br>
<h1><span style="background-color:lightgray" class="m-5">　<%= @show_admin_customer.last_name %><%= @show_admin_customer.first_name %>さんの会員詳細　</span></h1>
<br>
      <table border="0" class="mx-auto">
        <tr>
          <td height="50" width="200">会員ID</td>
          <td width="300"><%= @show_admin_customer.id %></td>
        </tr>
        <tr>
          <td height="50">氏名</td>
          <td width="300"><%= @show_admin_customer.last_name %> <%= @show_admin_customer.first_name %></td>
        </tr>
        <tr>
          <td height="50">フリガナ</td>
          <td><%= @show_admin_customer.last_name_kana %> <%= @show_admin_customer.first_name_kana %></td>
        </tr>
        <tr>
          <td height="50">郵便番号</td>
          <td><%= @show_admin_customer.postal_code %></td>
        </tr>
        <tr>
          <td height="50">住所</td>
          <td><%= @show_admin_customer.address %></td>
        </tr>
        <tr>
         <td height="50">電話番号</td>
          <td><%= @show_admin_customer.telephone_number %></td>
        </tr>
        <tr>
          <td height="50">メールアドレス</td>
          <td><%= @show_admin_customer.email %></td>
        </tr>
        <tr>
          <td height="50">会員ステータス</td>
              <% if @show_admin_customer.is_deleted == false %>
                <td><font color="green">有効</font></td>
              <% else %>
                <td><font color="gray">退会</font></td>
              <% end %>
        </tr>
        <tr>
         <td height="50"></td>
          <!--path(遷移先):admin/customers#edit(個人の会員情報編集)-->                        <!--path(遷移先):admin/orders#show(個人の注文履歴一覧)-->
          <td><%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success" %>　<%= link_to '注文履歴一覧を見る', admin_order_path, class: "btn btn-primary" %></td>
        </tr>
      </table>
<br>