config/routes.rb
Rails.application.routes.draw do

  devise_for :users
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: 'admin/sessions'
}

#管理者
  namespace :admin do
    resources :order_details, only: [:update]

    resources :orders, only: [:show, :update]

    resources :customers, only: [:index, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    root to: 'homes#top'
  end

#ユーザ
  scope module: :public do
  #namespace→scope moduleに変更
  #URLは変えず、ファイル構成だけ指定のパスにする(フォルダ名にはpublicをつけて、URLにはつけない)
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    #completeを追加　orders#showよりも上に記述しないとcompleteがid扱いされてしまう
    get 'orders/complete'

    #comfirmを追加
    post 'orders/comfirm'
    resources :orders, only: [:new, :create, :index, :show]#:comfirm, :complete, 

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]#:destroy_all, 

    #resources :customers, only: [:edit, :show, :update, :unsubscribe, :withdraw]
    #→customersはURLを変更しなければいけないのでresourcesは使えない
    #resourcesは基本の7つのみ使えるので、その他は手動で追加する(追加はto:不要)
    
    #customers
    #edit URLを「/customers/:id/edit」→「/customers/information/edit」に変更
    get 'customers/information/edit', to: 'customers#edit'
    #show URLを「/customers/:id(.:format)」→「customers/my_page」に変更
    get 'customers/my_page', to: 'customers#show'
    #update URLを「/customers/:id(.:format)」→「/customers/information」に変更
    patch '/customers/information', to: 'customers#update'
    #unsubscribeを追加、退会確認
    get '/customers/unsubscribe'
    #withdrawを追加、退会処理
    patch '/customers/withdraw'

    resources :items, only: [:index, :show]

    #'URL' => 'コントローラ#アクション', as: :Prefix(パスが入った変数)の変更
    get '/' => 'homes#top', as: :top
    get '/about' => 'homes#about'
  end
  
  #devise_for :admins
  #devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#resources :●●s, only: [:new, :index, :show, :edit, :create, :update, :destroy ]→７つだけ書ける
#その他は get(patchなどもOK) 'orders/show' => 'orders#show'と書く

app/views/layouts/_ganreselect.html.erb
<p id="notice"><%= notice %></p>

<!--作成途中-->
  <div class="container"><!-- px-5 px-sm-0-->
    <div class="row">
      <div class="col-md-3">
<!---->
  <table border="1"><!-- class="mx-auto"-->
    <thead>
        <tr height="50"><!-- bgcolor="lightgray"-->
            <th width="200">ジャンル検索</th>
        </tr>
    </thead>
  
    <tbody>
        <% @genres.each do |genre| %>
        <tr height="50">
          <td width="150">
              <%= link_to item_path(item.id) do %>
              <%= genre.name %>
              <% end %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
<!---->

app/views/layouts/application.html.erb
<!--共通部分-->
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--CSRF対策(クロスサイトリクエストフォージェリ)-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!-- FontAwesomeの読み込み log in→account→kits→cb~→copy-->
    <script src="https://kit.fontawesome.com/cb9c23a1e6.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg"><!--ヘッダーの背景を黒くするときnavbar-dark bg-darkを追加する-->
        <div class="container">
          <!--ロゴ-->
          <a class="navbar-brand; text-dark" href="/" ><h5>NaganoCake<%= image_tag 'logo', size: "50x50" %></h5></a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %><!--管理者側ログイン後 admin→テーブル名-->
            
              <li><!--admin/items#index　(current_user.id)-->
                <%= link_to admin_items_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">商品一覧</button>
                <% end %>
              </li>
  
              <li><!--admin/customers#index-->
                <%= link_to admin_customers_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">会員一覧</button>
                <% end %>
              </li>
  
              <li><!--admin/homes#top-->
                <%= link_to admin_root_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">注文履歴一覧</button>
                <% end %>
              </li>
  
               <li><!--admin/genres#index-->
                <%= link_to admin_genres_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">ジャンル一覧</button>
                <% end %>
              </li>

               <li><!--admin/sessions#destroy-->
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">ログアウト</button>
                <% end %>
              </li>

            <% elsif customer_signed_in? %><!--顧客側ログイン後 customer→テーブル名-->

              <li class="d-flex align-items-center justify-content-center">
                ようこそ、<%= current_customer.last_name %> <%= current_customer.first_name %>さん！
              </li>
            
              <li><!--public/customers#show　(current_user.id)-->
                <%= link_to customers_my_page_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">マイページ</button>
                <% end %>
              </li>
  
              <li><!--public/items#index-->
                <%= link_to items_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">商品一覧</button>
                <% end %>
              </li>
  
              <li><!--public/cart_items#index-->
                <%= link_to cart_items_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">カート</button>
                <% end %>
              </li>
  
               <li><!--public/sessions#destroy-->
                <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">ログアウト</button>
                <% end %>
              </li>

            <% else %><!--ログイン前-->

              <li class="nav-item"><!--public/homes#about-->
                <%= link_to about_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">About</button>
                <% end %>
              </li>
  
              <li><!--public/items#index-->
                <%= link_to items_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">商品一覧</button>
                <% end %>
              </li>
  
              <li><!--public/registrations#new-->
                <%= link_to new_customer_registration_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">新規登録</button>
                <% end %>
              </li>
  
              <li><!--public/sessions#new-->
                <%= link_to new_customer_session_path, class: "nav-link text-light" do %>
                <button type="button" class="btn btn-outline-secondary">ログイン</button>
                <% end %>
              </li>
            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <!--<footer align="center"><br>CopyRight Infratop.inc-->
    <!--</footer>-->
  </body>
</html>